### ISSUE TITLE
Python Import error in linux

### ISSUE THREAD

**Issue by TieSKey** [RSIA-LIESMARS-WHU/LSHBOX#1]
I'm having troubles to import this in linux. Trying to run the examples without any change yield the error:

Traceback (most recent call last):
  File "pylshbox-example.py", line 4, in <module>
    import pylshbox
ImportError: No module named pylshbox

for any of the 3 versions x86, x64, mingw. 

I tried recompiling but it only generates a pyd which is for windows (afaik).

Any idea on what could I be doing wrong? 
Thx in advance.

**Comment by primetang** [comment]
Hi,

Thank you very much for using LSHBOX and feedback.
In order to solve your problem, we have checked and updated LSHBOX in the past few days. Now, it can work well in Linux. If you recompiling it, you will get a py module which name is 'libpylshbox.so' in './build/py_module/linux', and it can be imported by Python.
Please try it again later. If you encounter other problems, please do not hesitate to contact us.

Best
