### ISSUE TITLE
Compile Errors in Ubuntu14.04 

### ISSUE THREAD

**Issue by LiliMeng** [RSIA-LIESMARS-WHU/LSHBOX#3]
[ 10%] Building CXX object tools/CMakeFiles/create_test_data.dir/create_test_data.cpp.o
In file included from /home/lili/workspace/LSHBOX/include/lshbox.h:44:0,
                 from /home/lili/workspace/LSHBOX/tools/create_test_data.cpp:29:
/home/lili/workspace/LSHBOX/include/lshbox/kdbqlsh.h: In member function ‘void 
Hi,
    Thanks a lot for contributing this LSHBOX! Currently there are the following compiling errors in Ubuntu14.04. Any suggestions ? Thanks! 
lshbox::kdbqLsh<DATATYPE>::Cluster(unsigned int, Eigen::MatrixXf)’:
/home/lili/workspace/LSHBOX/include/lshbox/kdbqlsh.h:273:19: error: ‘FLT_MAX’ was not declared in this scope
    float minVar = FLT_MAX;
                   ^
make[2]: *** [tools/CMakeFiles/create_test_data.dir/create_test_data.cpp.o] Error 1
make[1]: *** [tools/CMakeFiles/create_test_data.dir/all] Error 2
make: *** [all] Error 2

**Comment by primetang** [comment]
Thank you very much for using LSHBOX and feedback. We will check this problem and give you reply in time.

**Comment by primetang** [comment]
Hi,

In Ubuntu, 'FLT_MAX’ was not declared, we can use 'std::numeric_limits<float>::max()' instead of it. In fact, 'std::numeric_limits<float>::max()' is a better choice because it can be compatible with Windows and Linux. Thank you again for your feedback.
I have updated the corresponding code, and you can try again!

Best regards.
