### ISSUE TITLE
Some question about K means double bit quantization hashing

### ISSUE THREAD

**Issue by duming** [RSIA-LIESMARS-WHU/LSHBOX#7]
@primetang 
I noticed that in your code kdbqlsh.h
Instead of using double bit codes such as {11,01,00} to quantitate the feature vector, which proposed in "K-MEANS BASED DOUBLE-BIT QUANTIZATION FOR HASHING Hao Zhu".
You are using the sum of a random array to generate the hash value.
I looked at several other references you provide in the README file, but I can't find the source of this algorithm.

Could you please explain the algorithm that you are currently using to me.
Thank you.

  Your code:
```c++
            if (label == 0)
            {
                sum += rndArray[k][2 * i + 1];
            }
            if (label == 2)
            {
                sum += rndArray[k][2 * i];
            }
```

**Comment by IenLong** [comment]
Hi,
Actually, we put each point  into one of the L hash tables  after double-bit quantization to improve the search performance. The code you pasted above is used to determine into which hash table we should put a point. For more details, you can also reference to _A. Gionis, P. Indyk, and R. Motwani. Similarity search in high dimensions via hashing. Proceedings of the 25th International Conference on Very Large Data Bases (VLDB), 1999._ And we used {01, 00, 10} to quantitate a point since we think this should have the same quantization meaning as  {11,01,00}. Besides, this quantization method can contribute to reduce the amount of computation. Of course, it is very easy to modify the quantization code as {11,01,00}.
Regards,
Yang Long
